# 费用配置文件
# 按费用类别和国家分类

default_costs:
  # 美国留学费用 (USD)
  us:
    application:
      school_application_fees: 700   # 7所学校申请费 ($100 x 7)
      gre_exam_fee: 220              # GRE考试费
      gre_score_sending: 175         # GRE送分费 ($27 x 6 + 额外)
      toefl_exam_fee: 245            # TOEFL考试费
      toefl_score_sending: 240       # TOEFL送分费 ($20 x 6 + 额外)
      transcript_evaluation: 300     # WES/ECE成绩单认证

    visa_legal:
      f1_visa_fee: 185               # F1签证申请费
      sevis_fee: 350                 # SEVIS系统维护费
      interview_appointment_fee: 160 # 面试预约费
      visa_photo: 20                 # 签证照片
      passport_delivery: 30          # 护照快递费

    insurance_medical:
      health_insurance_per_year: 3000    # 年健康保险费
      dental_insurance_per_year: 500     # 年牙科保险费
      medical_checkup: 400               # 入学前体检费
      emergency_medical_fund: 2500       # 紧急医疗储备金

    transportation:
      round_trip_flights: 2250       # 往返机票费用
      baggage_fees: 450              # 行李托运费
      airport_pickup: 150            # 机场接送费
      local_transportation: 300      # 本地交通费

    accommodation:
      security_deposit: 2750         # 租房押金 (1-2个月)
      broker_fee: 1000               # 房屋中介费
      furniture_appliances: 2500     # 基本家具电器
      utility_deposits: 300          # 水电开户押金

    financial_services:
      bank_account_opening: 62       # 银行开户费
      credit_card_annual_fee: 100    # 信用卡年费
      remittance_fees: 1000          # 2年汇款手续费总计
      exchange_rate_loss: 1750       # 汇率波动损失

    communication:
      phone_plan_per_month: 55       # 月手机套餐费
      internet_per_month: 50         # 月网络费
      international_calls: 300       # 国际通话费总计

    study:
      textbooks: 1500                # 2年教材费用
      software_licenses: 450         # 专业软件许可费
      lab_materials: 350             # 实验材料费
      printing_copying: 200          # 打印复印费

    job_search:
      interview_travel: 1250         # 面试交通费
      professional_clothing: 550     # 职业装费用
      resume_optimization: 350       # 简历优化服务
      career_training: 1000          # 职业培训费

    emergency:
      family_emergency: 3500         # 家庭紧急情况储备
      personal_accidents: 2000       # 个人意外储备
      legal_consultation: 1250       # 法律咨询费

  # 加拿大留学费用 (CAD)
  canada:
    application:
      school_application_fees: 500   # 加拿大申请费较低
      study_permit_fee: 150          # 学习许可费
      biometrics_fee: 85             # 生物识别费
      transcript_evaluation: 200     # WES认证费用 (CAD)

    visa_legal:
      study_permit_fee: 150          # 学习许可费
      biometrics_fee: 85             # 生物识别费
      medical_exam: 300              # 体检费
      processing_fee: 50             # 处理费

    insurance_medical:
      health_insurance_per_year: 600    # 加拿大医疗保险相对便宜
      dental_insurance_per_year: 300    # 年牙科保险费
      medical_checkup: 250              # 入学前体检费
      emergency_medical_fund: 1000      # 紧急医疗储备金

    transportation:
      round_trip_flights: 1500       # 中加往返机票 (CAD)
      baggage_fees: 300              # 行李托运费
      airport_pickup: 100            # 机场接送费
      local_transportation: 200      # 本地交通费

    accommodation:
      security_deposit: 1800         # 租房押金 (1个月房租)
      broker_fee: 500                # 加拿大中介费较低
      furniture_appliances: 1500     # 基本家具电器
      utility_deposits: 200          # 水电开户押金

    financial_services:
      bank_account_opening: 25       # 加拿大开户更便宜
      remittance_fees: 600           # 2年汇款手续费
      exchange_rate_loss: 800        # 汇率波动损失

    communication:
      phone_plan_per_month: 50       # 月手机套餐费
      internet_per_month: 45         # 月网络费
      international_calls: 200       # 国际通话费

    study:
      textbooks: 800                 # 加拿大教材相对便宜
      software_licenses: 300         # 专业软件许可费
      lab_materials: 200             # 实验材料费
      printing_copying: 150          # 打印复印费

    job_search:
      interview_travel: 800          # 面试交通费
      professional_clothing: 400     # 职业装费用
      resume_optimization: 200       # 简历优化服务
      career_training: 600           # 职业培训费

    emergency:
      family_emergency: 2000         # 家庭紧急情况储备
      personal_accidents: 1000       # 个人意外储备
      legal_consultation: 800        # 法律咨询费

# 可调节的成本档位
cost_levels:
  # 节约型 - 降低非必需支出
  budget:
    adjustment_factors:
      accommodation: 0.8       # 选择更便宜住宿
      food: 0.7               # 自己做饭，减少外食
      entertainment: 0.3      # 减少娱乐支出
      emergency: 0.6          # 降低应急储备
      job_search: 0.5         # DIY简历，减少培训

  # 标准型 - 正常生活水平
  standard:
    adjustment_factors:
      accommodation: 1.0
      food: 1.0
      entertainment: 1.0
      emergency: 1.0
      job_search: 1.0

  # 舒适型 - 提高生活品质
  comfortable:
    adjustment_factors:
      accommodation: 1.3      # 选择更好住宿
      food: 1.2              # 更多外食和优质食材
      entertainment: 1.5     # 增加娱乐和旅游
      emergency: 1.2         # 提高应急储备
      job_search: 1.3        # 更多培训和服务

# 特殊费用项目
special_costs:
  # 陪读配偶费用 (如适用)
  spouse:
    visa_fee: 185            # 配偶签证费 (美国)
    insurance_per_year: 3000 # 配偶保险费
    living_cost_increase: 0.6 # 生活费增加系数

  # 子女教育费用 (如适用)  
  children:
    k12_tuition_per_year: 15000  # 国际学生K-12学费
    childcare_per_month: 1500    # 幼儿托管费用
    living_cost_increase: 0.8    # 生活费增加系数
